# Generated by Django 5.1.1 on 2024-09-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.TextField()),
                ('time', models.DateTimeField()),
                ('username', models.CharField(blank=True, default='', max_length=100)),
                ('password', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('bio', models.TextField(blank=True, default='')),
                ('prompt', models.TextField(blank=True, default='')),
                ('response', models.TextField(blank=True, default='')),
            ],
        ),
    ]
