# Generated by Django 4.2.16 on 2024-10-03 04:42

from django.db import migrations, models
import django.db.models.deletion
import log.crypto
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserUUID',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', log.crypto.EncryptedField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('password', log.crypto.EncryptedField(null=True)),
                ('name', log.crypto.EncryptedField(null=True)),
                ('bio', log.crypto.EncryptedField(null=True)),
                ('user_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.useruuid')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('prompt', log.crypto.EncryptedField(null=True)),
                ('response', log.crypto.EncryptedField(null=True)),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.userdata')),
            ],
        ),
        migrations.AddConstraint(
            model_name='userdata',
            constraint=models.UniqueConstraint(fields=('time', 'user_uuid'), name='unique_time_useruuid'),
        ),
    ]
