# Generated by Django 5.1.1 on 2024-09-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bio',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='password',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='prompt',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='response',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='username',
            field=models.BinaryField(),
        ),
    ]
