# Generated by Django 4.2.16 on 2024-09-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_alter_event_bio_alter_event_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bio',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='password',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='prompt',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='response',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='username',
            field=models.BinaryField(null=True),
        ),
    ]
